### ISSUE TITLE
Any example using json dictionaries?

### ISSUE THREAD

**Issue by fparaggio** [resin-io-playground/metalsmith-dynamic#3]
Hey guys thank you for your great work. Can you help me importing this data?

This is my code:

```
...
var dynamic = require('metalsmith-dynamic');
...
...
.use(dynamic({
  dictionaries: './dictionaries'
}))
...
```
## ./dictionaries/proj.json

```
[ {
      "id": 1,
      "name": "Beatiful joke",
      "link_name": "joke1",
      "icon":"joke.png"
  },
 {
      "id": 2,
      "name": "Smelly fart",
      "link_name": "smelly_f",
      "icon":"smelly.png"
}
]
```

I got the error

```
Error: Cannot find module './dictionaries/proj'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:20:19)
  at Function.Dicts.fromDir (/vagrant/node_modules/metalsmith-dynamic/lib/dictionaries.coffee:73:25)
  at Dicts (/vagrant/node_modules/metalsmith-dynamic/lib/dictionaries.coffee:10:18)
  at expand (/vagrant/node_modules/metalsmith-dynamic/lib/index.coffee:11:11)
  at Ware.<anonymous> (/vagrant/node_modules/metalsmith-dynamic/lib/index.coffee:110:5)
  at Ware.<anonymous> (/vagrant/node_modules/wrap-fn/index.js:45:19)
  at Immediate.next (/vagrant/node_modules/ware/lib/index.js:85:20)
  at Immediate._onImmediate (/vagrant/node_modules/wrap-fn/index.js:121:18)
  at tryOnImmediate (timers.js:534:15)
  at processImmediate [as _immediateCallback] (timers.js:514:5)

make: *** [develop] Error 1
```

---

**Comment by emirotin** [comment]
Hi. Hm, that's interesting. Importing JSON files should just work.

Maybe it just fails beсause of the path? What happens if you drop the `./` from the dicts path?

If that doesn't help then two questions:
- what version of `node` do you use?
- if you convert your file to `CommonJS` module (change the extension, add `module.exports =` to the beginning) does it work?

**Comment by fparaggio** [comment]
Thanks for your prompt reply. here the results... 
- Node v5.12.0
- if i drop the `./` i get the same error
- i tried as module with the following code

## dictionaries/proj.js

```
module.exports = {
  a: [
  {
      "id": 1,
      "name": "Beatiful joke",
      "link_name": "joke1",
      "icon":"joke.png"
  },
 {
      "id": 2,
      "name": "Smelly fart",
      "link_name": "smelly_f",
      "icon":"smelly.png"
}
]
};
```

i obtain exactly the same error

```
Error: Cannot find module 'dictionaries/proj'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:20:19)
  at Function.Dicts.fromDir (/vagrant/node_modules/metalsmith-dynamic/lib/dictionaries.coffee:73:25)
  at Dicts (/vagrant/node_modules/metalsmith-dynamic/lib/dictionaries.coffee:10:18)
  at expand (/vagrant/node_modules/metalsmith-dynamic/lib/index.coffee:11:11)
  at Ware.<anonymous> (/vagrant/node_modules/metalsmith-dynamic/lib/index.coffee:110:5)
  at Ware.<anonymous> (/vagrant/node_modules/wrap-fn/index.js:45:19)
  at Immediate.next (/vagrant/node_modules/ware/lib/index.js:85:20)
  at Immediate._onImmediate (/vagrant/node_modules/wrap-fn/index.js:121:18)
  at tryOnImmediate (timers.js:534:15)
  at processImmediate [as _immediateCallback] (timers.js:514:5)

make: *** [develop] Error 1
```

thank you in advance very much for your time

**Comment by emirotin** [comment]
OK so we know it's not JSON specific. Can you share the full project with me or create a simplified demo that reproduces the bug?

**Comment by emirotin** [comment]
Also BTW you have the extra `a:` in your CommonJS example, it shouldn't be there. The exports should be an array itself.

**Comment by fparaggio** [comment]
Eugene, I created a simplified demo here https://github.com/fparaggio/test-for-metalsmith-dynamic
however i tried also without the a: . TPlease let me know.

**Comment by emirotin** [comment]
Ah, you need to specify the full path, like `dictionaries: __dirname + '/dictionaries'`. Otherwise I think it tries to resolve it like "proj submodule from a globally available dictionaries module" when without a dot, and relative to the `ms-dynamic` main module when with dot.
